language: php
php:
  - 8.0
  - nightly
env:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""
matrix:
  fast_finish: true
  allow_failures:
     - php: nightly
before_script:
  - composer update $PREFER_LOWEST
script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit
after_success: ./vendor/bin/php-coveralls -v
